name: Trivy Security Scan

on:
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/trivy-scan.yaml'
    branches:
      - main

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'my-app:latest'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          
          
