name: Trivy Security Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
